### ISSUE TITLE
Language change abnormal

### ISSUE THREAD

**Issue by lemotw** [abc873693/NKUST-AP-Flutter#4]
I encounter a problem when I press "關於我們" then go to the software license.
The system language will turn into English.

![Imgur](https://i.imgur.com/7CEAL9Z.png)

**Comment by abc873693** [comment]
Because license page will change app locale ,will be fixed in the next release.

**Comment by abc873693** [comment]
Fix in https://github.com/abc873693/NKUST-AP-Flutter/pull/8
