### ISSUE TITLE
Class Schedule formatting is off

### ISSUE THREAD

**Issue by vn7n24fzkq** [abc873693/NKUST-AP-Flutter#5]
- As title
![image](https://user-images.githubusercontent.com/20241522/47413186-33499680-d7a0-11e8-92f8-fe005d00e2e0.png)

Platform :
- Nokia 5.1 Plus

- Android 8.1
- Kernel version : 4.4.95
- Model : TA-1105

_Sent from my Nokia 5.1 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by abc873693** [comment]
Fix in https://github.com/abc873693/NKUST-AP-Flutter/pull/8
